# Generated by Django 2.2.9 on 2020-02-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('book_intro', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='books/image')),
            ],
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('book_intro', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='books/image')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
            ],
        ),
    ]
