# Generated by Django 2.2.9 on 2020-02-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='books/image'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='image',
            field=models.ImageField(null=True, upload_to='books/image'),
        ),
    ]
