# Generated by Django 2.2.9 on 2020-02-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200209_2036'),
        ('books', '0002_auto_20200201_1015'),
    ]

    operations = [
    ]
