# Generated by Django 2.2.9 on 2020-02-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_ban_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rate_date',
        ),
    ]
